### PR TITLE
Change importlib_metadata to importlib.metadata

### PR DESCRIPTION
**Pull request by nschimmoller**

### CODE REVIEW

**Comment by nschimmoller** [comment]
@zware this fixed my make test issues locally. Can you confirm on your end?

**Review by zware — APPROVED** [review]
I'm a little reticent to leave a public-looking `metadata` name laying around, but otherwise LGTM :)

**Comment by nschimmoller** [comment]
@zware happy to change it to something different. Just know guidance is to not abbreviate the import names for easier code maintenance. Let me know if you have any ideas :)

**Comment by nschimmoller** [comment]
@zware another thought should we add make test to part of the CI workflow?

**Comment by zware** [comment]
I wouldn't abbreviate, but maybe leave it as `_importlib_metadata`?  Alternately, we could add a properly-populated `__all__`, but that brings its own maintenance headaches.

I don't think we should try to run `make test` directly in CI; we do the same tests on the same Python versions, just with a slightly different setup.  To use `make test` in CI, we would need to completely redo CI (again :)).

**Comment by nschimmoller** [comment]
@zware cool I'll update it to `_importlib_metadata` and also change version to a `23.12.11.dev0` version

**Pull request merged**
