### PR TITLE
Update to main branch of debian for most recent updates

### PR DESCRIPTION
**Pull request by nschimmoller**
Latest revision of Debian (4.15.0) was released on 2023-04-27, however several changes, including a large update I personally made for the ISO3166-2.json have been made since then and would be great to include for our users.

Reaching out to Debian maintainer to determine if a new release is in order.

### CODE REVIEW

**Comment by nschimmoller** [comment]
Addresses question from #188. Planning to merge this post merge of #183 staging for now

**Comment by brycedewitt** [comment]
Thanks for tackling that.

I was about to suggest getting into regions with multiple administrative languages next, but see you and Tobias are once again [a step ahead](https://salsa.debian.org/iso-codes-team/iso-codes/-/merge_requests/34). Looking forward to all these updates, let me know if you you need a second set of eyes on anything 👍

**Comment by nschimmoller** [comment]
> Thanks for tackling that.
> 
> I was about to suggest getting into regions with multiple administrative languages next, but see you and Tobias are once again [a step ahead](https://salsa.debian.org/iso-codes-team/iso-codes/-/merge_requests/34). Looking forward to all these updates, let me know if you you need a second set of eyes on anything 👍

@brycedewitt what is your thought on that proposed format? 

FWIW the scrapper project that I have is going pretty well. I'm amending it to also pull in ISO 3166-1 and most likely ISO 3166-3 for any changes to those standards. 

Once done with that I'm planning on moving on to scraping the remaining standards pycountry supports so there is a very easy way to run a script to gather all up to date standards, and hopefully automate the commit process to iso-codes

**Comment by zware** [comment]
I think we should wait for an upstream release before updating here.  Much easier to keep track of that way.

**Comment by nschimmoller** [comment]
> I think we should wait for an upstream release before updating here. Much easier to keep track of that way.

Makes sense asking Tobias about that now :)

**Comment by nschimmoller** [comment]
@zware confirmed with Tobias that he is waiting a few days for language translations from weblate to flow through. Should have a new revision release upcoming in the next week or so.

**Comment by brycedewitt** [comment]
@zware thanks for cleaning up on these 👍

**Pull request closed without merging**
